In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
cd /content/drive/My Drive/Colab Notebooks

/content/drive/My Drive/Colab Notebooks


In [ ]:
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn import neighbors
from matplotlib.colors import ListedColormap, BoundaryNorm
import matplotlib.patches as mpatches
from PIL import Image
from imutils import paths
import os

In [ ]:
# grab all image paths in the input dataset directory, then initialize
# our list of images and corresponding class labels
print("[INFO] loading images...")
imagePaths = paths.list_images("Data Cocoa Ripe")
data = []
labels = []

[INFO] loading images...


In [ ]:
# loop over our input images
for imagePath in imagePaths:
	# load the input image from disk, resize it to 64x64 pixels, scale
	# the pixel intensities to the range [0, 1], and then update our
	# images list
	image = Image.open(imagePath)
	image = np.array(image.resize((64,64))) / 255.0
	data.append(image)

	# extract the class label from the file path and update the
	# labels list
	label = imagePath.split(os.path.sep)[-2]
	labels.append(label)

In [ ]:
print(labels)

['Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Mature', 'Imature', 'Imature', 'Imature', 'Imature', 'Imature', 'Imature', 'Imature', 'Imature', 'Imature', 'Imature', 'Imature', 'Imature', 'Imature', 'Imature', 'Imature', 'Imature', 'Imature', 'Imature', 'Imature', 'Imature', 'Imature', 'Imature', 'Imature', 'Imature', 'Imature', 'Imature', 'Im

In [ ]:
# perform a training and testing split, using 75% of the data for
# training and 25% for evaluation
(trainX, testX, trainY, testY) = train_test_split(np.array(data),	np.array(labels), test_size=0.15)
print(trainX.shape)
print(testX.shape)
print(trainY.shape)
print(testY.shape)

(181, 64, 64, 3)
(32, 64, 64, 3)
(181,)
(32,)


In [ ]:
trainX = trainX.reshape(181,3*64*64)
testX = testX.reshape(32,3*64*64)

In [ ]:
# Create classifier objet
knn = KNeighborsClassifier(n_neighbors = 5)

# Train the classifier using train data
knn.fit(trainX, trainY)

KNeighborsClassifier()

In [ ]:
# make predictions on our data and show a classification report
print("[INFO] evaluating...")
predictions = knn.predict(testX)
print(predictions)

[INFO] evaluating...
['OverMature' 'OverMature' 'Imature' 'Imature' 'Mature' 'Mature'
 'OverMature' 'OverMature' 'OverMature' 'OverMature' 'OverMature'
 'OverMature' 'OverMature' 'OverMature' 'Imature' 'Mature' 'OverMature'
 'OverMature' 'Mature' 'Mature' 'Imature' 'Imature' 'Mature' 'OverMature'
 'Mature' 'OverMature' 'Mature' 'Imature' 'OverMature' 'Imature' 'Mature'
 'OverMature']


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
print(confusion_matrix(testY, predictions))

[[ 6  3  0]
 [ 1  4  3]
 [ 0  2 13]]


In [ ]:
print(classification_report(testY, predictions))

              precision    recall  f1-score   support

     Imature       0.86      0.67      0.75         9
      Mature       0.44      0.50      0.47         8
  OverMature       0.81      0.87      0.84        15

    accuracy                           0.72        32
   macro avg       0.70      0.68      0.69        32
weighted avg       0.73      0.72      0.72        32



In [ ]:
import cv2
import matplotlib.pyplot as plt

gambar = 'Salinan S5.jpg'
image = cv2.imread(gambar)
plt.imshow(image)
plt.show()

In [ ]:
image_test=Image.open(gambar)
image_test=np.array(image_test.resize((64,64))) / 255.0
image_test.shape

(64, 64, 3)

In [ ]:
image_test=np.expand_dims(image_test, axis=0)
image_test.shape

(1, 64, 64, 3)

In [ ]:
image_test = image_test.reshape(1 ,3*64*64)

In [ ]:
predict = knn.predict(image_test)

In [ ]:
print(predict)

['Mature']


In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV

param_grid = {'n_neighbors': np.arange(1,10)}

knn_clf = GridSearchCV(KNeighborsClassifier(), param_grid, cv = 3, scoring='accuracy')

knn_clf.fit(trainX, trainY)
knn_clf.best_params_

{'n_neighbors': 6}

In [ ]:
knn_clf = KNeighborsClassifier(n_neighbors=5)
knn_clf.fit(trainX, trainY)

pred_clf = knn_clf.predict(testX)

round(accuracy_score(testY, pred_clf),3)

0.815